### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by rytilahti**
First step towards a new release. This PR also includes deprecation of `identify` and `features` of SmartDevice, and it also updates the README file. Please feel free to scrutinize before merging & tagging!

### CODE REVIEW

**Comment by mweinelt** [comment]
I currently don't have time to do a review or contribute, sorry.

**Review by kirichkov — APPROVED** [review]
I haven't done any real world testing since I only have the plug, but there are very few code changes since the last pull, so unless there's a syntax error somewhere I missed, it looks good.

Great job on the Readme and Changelog! 👍

**Comment by gollo** [comment]
I just raised PR #89 to fix some stuff in the CLI (bulb related).
Also, everything else works (from the CLI) for the LB110 and HS100.

**Comment by rytilahti** [comment]
I moved the real changes out from this commit and pushed them to master. This PR is just for the release preparation. One problem I noticed is that as we are using `features` internally in `has_emeter` it will emit warnings even on normal use. That should be fixed before the release too.

**Comment by rytilahti** [comment]
Release is now done, thanks for everyone involved! :)

**Pull request merged**
