### PR TITLE
Add kelvin range for KL130

### PR DESCRIPTION
**Pull request by dieselrabbit**
This addition gets this bulb to work with home assistant.

### CODE REVIEW

**Review by kirichkov — APPROVED** [review]
🎉

**Comment by rytilahti** [comment]
Could you also add the range for KL120 (seems to be the same as LB120: https://www.tp-link.com/uk/products/details/cat-5609_KL120.html) to this same commit?

**Comment by dieselrabbit** [comment]
Added KL120, though I can't test as I don't have that bulb.
Hope I did this right. Git newbie and this is my first pull request.

**Comment by rytilahti** [comment]
It is good, thanks! :1st_place_medal:

**Pull request merged**
