### PR TITLE
Update readme to include a note about abandonment

### LINKED ISSUE #195: Archive this repository
And link prominently to the new one.

### PR DESCRIPTION
**Pull request by rytilahti**
Fixes #195

### CODE REVIEW

**Review by kirichkov — APPROVED** [review]

**Comment by kirichkov** [comment]
Isn't it time to archive the repository?

**Comment by rytilahti** [comment]
It would be, but @GadgetReactor is the only one who can do that.

**Comment by kirichkov** [comment]
:-/ Wiping the repo and putting only a README.md with a link to the new one, might be the only way to go.

**Comment by rytilahti** [comment]
I think it's fine to leave it as it is (that's why I think the pypi package should also stay as it is), maybe someone wants to use non-asyncio version and/or fork the project at some point.

**Pull request merged**
