### PR TITLE
Add device discovery

### PR DESCRIPTION
**Pull request by rytilahti**
These commits add ability to discover devices in the local network, and adds an example script showing its usage. Doesn't use TDDP, but fulfils #9 for local discovery.

The code has been tested with HS110.

### CODE REVIEW

**Comment by kirichkov** [comment]
👍

**Comment by kirichkov** [comment]
I'm not able to get this working under raspbian and Ubuntu. What OS did you use to get successful discovery?

I'm clearly seeing the response from the plug in tcpdump, but the discovery times out.

**Comment by rytilahti** [comment]
Raspbian here. The discovery is supposed to time out (it's udp, so we have to quit listening for responses at some point), but it should print out the results after that.

**Comment by kirichkov** [comment]
I'm getting this, but I clearly see the response from the Plug in tcpdump. It's important to note that my plug is on a separate VLAN and my hass box also has a vlan interface on the same VLAN, this might be related.

```
>>> from pyHS100 import TPLinkSmartHomeProtocol
>>> TPLinkSmartHomeProtocol.discover()
Got exception timed out
Traceback (most recent call last):
  File "/home/kirichkov/dev/hass/pyHS100/pyHS100/protocol.py", line 99, in discover
    data, addr = sock.recvfrom(4096)
socket.timeout: timed out
[]
>>> 
```

**Comment by rytilahti** [comment]
It works only inside one network, broadcasts are not forwarded to other networks by routers.

**Comment by kirichkov** [comment]
While investigating non-related issue, I think a socket.bind("ip_of_vlan") would fix my issue. I think why it's failing is because python attaches to the first interface listening for responses, and not to all interfaces.

**Comment by rytilahti** [comment]
You can't receive broadcasts between vlan segments/networks, that's just how it works with routers. If it is in the same network (even from many), you can try if sock.bind("", <port>) helps. That'll bind on all available interfaces.

**Comment by kirichkov** [comment]
Nope, what you suggest does not work. If I do bind on the vlan interface's IP address, it works!

**Pull request merged**
