### PR TITLE
Add precommit hooks & tox env to enforce code structure, add azure pi…

### PR DESCRIPTION
**Pull request by rytilahti**
…pelines

Instead of leveraging hound & travis, add an option for azure pipelines,
which may replace the former in the future.

This also streamlines the contributing guidelines by:
* Adding pre-commit hooks to run isort, black, flake8, mypy
* Adding lint environment to allow checks to be run `tox -e lint`

This also contains a major cleanup to the SmartStrip handling which was due. Basically most of the functionality is offered per plug basis and the index-based helper methods are removed.
After seeing #184 I thought I should push this in as it is for comments before the codebase diverges too much.

Other changes include:
* version is now accessible for the package (`pyHS100.__version__` as per pep8), bumped version to 0.40.dev0.
* require python 3.6 (for variable annotations and maybe also for other reasons)

### CODE REVIEW

**Comment by rytilahti** [comment]
So, I also noticed that I cannot create commit hooks as I'm merely a contributor in this repository.. @GadgetReactor would you mind transfering the ownership of this repository either to me or to a new `pyhs100` organization?

**Comment by basnijholt** [comment]
This is great! Unfortunately, the work in #184 will result in a lot of merge conflicts.

@rytilahti what about merging our works in #184 and continuing there to avoid a lot of work later?

**Comment by kirichkov** [comment]
Sorry! I noticed the issue about the commit hooks and thought this is on hold until then!

**Review by kirichkov — APPROVED** [review]
Looks good.

**Comment by rytilahti** [comment]
This is already in our new repository (https://github.com/python-kasa/python-kasa), closing.

**Pull request closed without merging**
