### PR TITLE
API and tests cleanup

### PR DESCRIPTION
**Pull request by rytilahti**
I'm creating this PR to get some feedback on the proposed API changes. The current API remains intact (with some minor changes related to error-reporting and available constants), but I'm hoping we can drop the property-setter based API in the future. The main goal was to make the API consistent and nicer to use for 3rd parties, while making writing tests more manageable. This also allows easier implementation of some previously wished features.

This is still WIP (HS300 has to be rebased in, and tests need to be made runnable on real devices) before merging it. The version should be bumped to 0.4.0 with these changes.

Feel free to test and contribute new fixture files (`pyhs100 dump-discover` can be used to do that).

Related issues #97, #146,  #147 and PRs #145, #119, #98.

The commit messages explaining the changes can be found below.

    Cleanup tests and improve test coverage
    
    * Make writing tests easier by sharing code for common implementations
    * Instead of storing test data inside python files, dump-discover based information is used
      * This will simplify adding new tests and remove code duplication
      * fixtures are based on https://github.com/plasticrake/tplink-smarthome-simulator

    Major API cleanup
    
    Properties shall no more change the state of the device, this work in still in progress, the main goal being making the API more user-friendly and to make implementing new features simpler.
    
    The newly deprecated functionality will remain working and will simply warn the user about deprecation.
    Previously deprecated 'features' property and 'identify' method are now finally removed.
    
    Deprecate and replace the following property setters:
    * state with turn_on() and turn_off()
    * hsv with set_hsv()
    * color_temp with set_color_temp()
    * brightness with set_brightness()
    * led with set_led()
    * alias with set_alias()
    * mac with set_mac()
    
    And getters:
    * state with is_on and is_off
    
    The {BULB,PLUG}_STATE_{ON,OFF} is simplified to STATE_ON and STATE_OFF, UNKNOWN state is removed.
    These are now deprecated and will be removed in the future.
    * is_on and is_off can be used to check for the state
    * turn_on() and turn_off() for changing the device state.
    
    Trying to use functionality not supported by the device will cause SmartDeviceExceptions instead of failing silently and/or returning None.
    This includes, e.g., trying to set a color temperature on non-supported bulb.
    
    ValueErrors are raised instead of SmartDeviceExceptions where appropriate (e.g. when trying to set an invalid hsv or brightness).
    
    New enum type DeviceType is added to allow detecting device types without resorting to isinstance() calling. SmartDevice class' device_type property can be used to query the type. is_plug and is_bulb helpers are added.

    Add new cli commands: raw_command and dump_discover
    
    - raw_command can be used to execute raw commands with given parameters
      * Useful for testing new calls before implementing them properly
    
    - dump_discover can be used to dump the device discovery information (into a file)
      * The discovery is extended to request more modules and methods from devices
        * smartlife.iot.dimmer get_dimmer_parameters
        * smartlife.iot.common.emeter get_realtime
        * smartlife.iot.smartbulb.lightingservice get_light_state
      * This is used to dump more information for proper tests, and will also allow better discovery in the future
    
    This commit contains also some documentation updates and dropping click_datetime in favor of click's built-in datetime

### CODE REVIEW

**Comment by rytilahti** [comment]
`pytest --cov=pyHS100 --cov-report=html pyHS100/tests/fixture_tests.py` is probably the easiest way to run the tests and check the coverage for now. The existing tests work still fine, but I hope they can be dropped in favor of the fixture based ones.

**Comment by martinevong** [comment]
I ran this pull request to get some info on the HS220, and there is a misnamed variable `type` on lines 122 and 124; it should be `type_`. I couldn't update the code though. Attached is the output of running `pyhs100 dump_discover`, with a few lines edited for privacy.

[HS220(US)_1.0.log](https://github.com/GadgetReactor/pyHS100/files/2843560/HS220.US._1.0.log)

**Comment by rytilahti** [comment]
@poiyo I fixed that, and thanks for the discovery file, I added it also to the tests. Could you though verify if the `latitude_i` and `longitude_i` values are integers or floats?

**Comment by martinevong** [comment]
@rytilahti They're both 6 digit ints.

**Comment by jimboca** [comment]
What needs to be done to complete this request so it can be merged?

**Comment by newAM** [comment]
Wow this is some serious cleanup, I really like the move to JSON files and pytest fixtures for the devices!

**Comment by rytilahti** [comment]
@jimboca I would like to clean-up the SmartStrip interface before getting this merged, it was a bad idea from my side to encourage method overriding instead of having separate controls for separate strips.

On top of that, I'm currently working in adding a very simple cache for the "getters" to avoid having loads of calls for querying every single piece of information from the sysinfo & light states. After those are done and we'll get some testers to verify that all is still working fine, I'd like to get this merged and make a new major release!

@newAM indeed, I hope it makes it much nicer to write tests when needed! I think we can add some new features for lights (I currently have access to KL120 bulbs) which have been postponed due to API issues.

**Comment by jimboca** [comment]
Sorry I just saw this, thanks for the response.  It will be great if this can get done.  Let us know if you need help, I don't have much time the next few weeks but I could try.

**Comment by rytilahti** [comment]
Sorry for the spam, I made some mistakes while rebasing this... But I think we need to get this merged and fix the remaining issues in separate PRs, this is already getting way too large to review properly. I added a simple cache for queries which is enabled per default with TTL of three seconds, this is only used for commands starting with `get_` (e.g., get_sysinfo) and will make using the API much smoother. homeassistant was spamming this pretty hard when reading the properties separately, potentially causing availability issues (https://github.com/home-assistant/home-assistant/issues/23045 may be related).

I also took the liberty to run black on the whole codebase, and added a precommit hook for it so that the code conforms with it in the future.

**Comment by kirichkov** [comment]
That's a huge one. I've reviewed to the best of my abilities, and didn't see any issues.

**Comment by rytilahti** [comment]
Ok, thanks for taking a look! Let's merge this and try to get some feedback (and to allow proceedings on other open PRs) :-)

**Pull request merged**
