### PR TITLE
Updated valid range to 360

### PR DESCRIPTION
**Pull request by zackoch**
with it set to 359 it will not show the color red. Just tested this with a buddies bulb - same model/fw
https://imgur.com/a/kSNZIuL

### CODE REVIEW

**Comment by rytilahti** [comment]
As I have no device for testing, I'm going to trust you and merge this after the tests are fixed! Thanks :+1:

**Comment by nikoladze** [comment]
I just tested this with my LB130 and i can confirm it works with this PR!

**Comment by rytilahti** [comment]
@zackoch Any news on updating the tests to pass? I'd be happy to merge this then :-)

**Comment by zackoch** [comment]
@rytilahti I am unsure how to do that, but it looks like someone just figured it out :)

**Comment by rytilahti** [comment]
No worries, thanks for the PR, I'll close this in favor of #153! :-)

**Pull request closed without merging**
